# Generated by Django 5.1.2 on 2025-04-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lecturematerials_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '강의'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='materials/'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.CreateModel(
            name='AssignmentMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_materials', to='courses.course')),
                ('files', models.ManyToManyField(related_name='assignment_lectures', to='courses.file')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_materials', to='courses.course')),
                ('files', models.ManyToManyField(related_name='exam_lectures', to='courses.file')),
            ],
        ),
    ]
